### PR TITLE
doc: Document all public APIs

### LINKED ISSUE #92: Document all public APIs
`pip-audit` has public APIs that should be fully documented.

We should use a tool like [`interrogate`](https://interrogate.readthedocs.io/en/latest/) to ensure docstring coverage.

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Closes #92

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
Current linting output:
```
(env) tetsuo@Alexs-MacBook-Pro pip-audit % make lint
. env/bin/activate && \
		black setup.py pip_audit/dependency_source/requirement.py pip_audit/dependency_source/interface.py pip_audit/dependency_source/__init__.py pip_audit/dependency_source/pip.py pip_audit/dependency_source/resolvelib/__init__.py pip_audit/dependency_source/resolvelib/pypi_provider.py pip_audit/dependency_source/resolvelib/resolvelib.py pip_audit/version.py pip_audit/audit.py pip_audit/util.py pip_audit/__init__.py pip_audit/cli.py pip_audit/format/interface.py pip_audit/format/__init__.py pip_audit/format/columns.py pip_audit/format/json.py pip_audit/service/interface.py pip_audit/service/__init__.py pip_audit/service/osv.py pip_audit/service/pypi.py pip_audit/virtual_env.py pip_audit/state.py test/dependency_source/test_requirement.py test/dependency_source/__init__.py test/dependency_source/test_resolvelib.py test/dependency_source/test_pip.py test/dependency_source/test_interface.py test/test_version.py test/conftest.py test/test_audit.py test/test_virtual_env.py test/format/conftest.py test/format/__init__.py test/format/test_columns.py test/format/test_json.py test/service/test_interface.py test/service/test_pypi.py test/service/test_osv.py test/test_cli.py && \
		isort setup.py pip_audit/dependency_source/requirement.py pip_audit/dependency_source/interface.py pip_audit/dependency_source/__init__.py pip_audit/dependency_source/pip.py pip_audit/dependency_source/resolvelib/__init__.py pip_audit/dependency_source/resolvelib/pypi_provider.py pip_audit/dependency_source/resolvelib/resolvelib.py pip_audit/version.py pip_audit/audit.py pip_audit/util.py pip_audit/__init__.py pip_audit/cli.py pip_audit/format/interface.py pip_audit/format/__init__.py pip_audit/format/columns.py pip_audit/format/json.py pip_audit/service/interface.py pip_audit/service/__init__.py pip_audit/service/osv.py pip_audit/service/pypi.py pip_audit/virtual_env.py pip_audit/state.py test/dependency_source/test_requirement.py test/dependency_source/__init__.py test/dependency_source/test_resolvelib.py test/dependency_source/test_pip.py test/dependency_source/test_interface.py test/test_version.py test/conftest.py test/test_audit.py test/test_virtual_env.py test/format/conftest.py test/format/__init__.py test/format/test_columns.py test/format/test_json.py test/service/test_interface.py test/service/test_pypi.py test/service/test_osv.py test/test_cli.py && \
		flake8 setup.py pip_audit/dependency_source/requirement.py pip_audit/dependency_source/interface.py pip_audit/dependency_source/__init__.py pip_audit/dependency_source/pip.py pip_audit/dependency_source/resolvelib/__init__.py pip_audit/dependency_source/resolvelib/pypi_provider.py pip_audit/dependency_source/resolvelib/resolvelib.py pip_audit/version.py pip_audit/audit.py pip_audit/util.py pip_audit/__init__.py pip_audit/cli.py pip_audit/format/interface.py pip_audit/format/__init__.py pip_audit/format/columns.py pip_audit/format/json.py pip_audit/service/interface.py pip_audit/service/__init__.py pip_audit/service/osv.py pip_audit/service/pypi.py pip_audit/virtual_env.py pip_audit/state.py test/dependency_source/test_requirement.py test/dependency_source/__init__.py test/dependency_source/test_resolvelib.py test/dependency_source/test_pip.py test/dependency_source/test_interface.py test/test_version.py test/conftest.py test/test_audit.py test/test_virtual_env.py test/format/conftest.py test/format/__init__.py test/format/test_columns.py test/format/test_json.py test/service/test_interface.py test/service/test_pypi.py test/service/test_osv.py test/test_cli.py && \
		mypy pip_audit && \
		interrogate -c pyproject.toml . && \
		git diff --exit-code
All done! ✨ 🍰 ✨
40 files left unchanged.
Success: no issues found in 22 source files
RESULT: FAILED (minimum: 80.0%, actual: 38.9%)
make: *** [lint] Error 1
```

**Comment by woodruffw** [comment]
We can tag team this -- I went ahead and added `interrogate` to the `setup.py`, and I'll start documenting the dep source and auditing APIs.

**Comment by woodruffw** [comment]
As of b23a3a7:

```
RESULT: FAILED (minimum: 80.0%, actual: 45.2%)
```

(My local doc coverage started in the 20% range, so I'm not sure what's up with that.)

**Comment by woodruffw** [comment]
57a0981:

```
RESULT: FAILED (minimum: 80.0%, actual: 63.9%)
```

**Comment by tetsuo-cpp** [comment]
> My local doc coverage started in the 20% range, so I'm not sure what's up with that

Ah that's my bad. I had some code in my project root that I was using to test editable requirements. Our coverage matches up now.

**Comment by tetsuo-cpp** [comment]
```
RESULT: PASSED (minimum: 80.0%, actual: 100.0%)
```

**Pull request merged**
