### PR TITLE
pre-commit

### LINKED ISSUE #252: support pre-commit (add a small file called .pre-commit-hooks.yaml)
**Is your feature request related to a problem? Please describe.**

no

**Describe the solution you'd like**

add a small file called `.pre-commit-hooks.yaml` in the root of the project, follow [this](https://pre-commit.com/#new-hooks)

**Describe alternatives you've considered**

using `pre-commit` running `pip-audit` globally installed on the system (not ideal for teams)

**Additional context**

join a [massive ecosystem](https://pre-commit.com/hooks.html) of easy-to-use hooks

### PR DESCRIPTION
**Pull request by tal66**
added `.pre-commit-config.yaml`.

tldr usage:
set up the git hook scripts: `pre-commit install`, and this will run when `git commit`.

extra:
can use 
`pre-commit run <hook> --files <file>` to run just this hook on just this file.
`pre-commit run -a` (short for `--all-files`). 
`pre-commit autoupdate` to update all rev's in the yaml

(closes #252)

### CODE REVIEW

**Comment by woodruffw** [comment]
I think there's been a misunderstanding -- I thought the point of #252 was to make `pre-commit` support `pip-audit`, and not the other way around. Did I understand that right @chrisdlangton?

**Comment by tal66** [comment]
You're probably right. I added config instead of hooks. misread

**Comment by chrisdlangton** [comment]
Indeed, have pip-audit be included into the pre-commit list of supported hooks

So that a pre-commit user (repo) can target pip-audit repo url directly as a task in their own hooks config on their own projects

Currently user's of pre-commit have to have pip-audit run in local/global mode as pip-audit repo is not yet ready to be referenced by repo url

**Comment by woodruffw** [comment]
Closing for now, then. @tal66 feel free to open a separate PR for https://github.com/trailofbits/pip-audit/pull/254#issuecomment-1112774708, if you'd like!

**Pull request closed without merging**
