### PR TITLE
Added conda install instruction

### PR DESCRIPTION
**Pull request by sugatoray**
This closes issue #199.

- [x] Readme file was updated (installation section)
- [x] Added some badges (conda-forge, license). 

---

The PR (https://github.com/conda-forge/staged-recipes/pull/17235) for adding `pip-audit` to conda-forge was recently merged.

image

### CODE REVIEW

**Comment by sugatoray** [comment]
cc: @woodruffw

> Please see my comments [here](https://github.com/trailofbits/pip-audit/issues/199#issuecomment-991489223).

**Comment by woodruffw** [comment]
Thanks for looking into that! Yeah, it seems that Repology doesn't index Conda; oh well.

Otherwise LGTM; I'm going to tweak the PR slightly to emphasize that the conda package is community maintained.

**Comment by sugatoray** [comment]
@woodruffw I could add you to the list of maintainers of the conda-forge package. This will allow you to update both PyPI and conda-forge pretty much the same time. There are only some minor changes that need to be made during each new release. I can walk you through the steps, if you would like. Please let me know.

**Comment by woodruffw** [comment]
I don't mind being added as a maintainer, although Conda's structure means that we'll still likely consider it a "community maintained" distribution rather than an "official" one like the PyPI distribution.

CCing @di, since he may want to be marked as a maintainer as well.

**Pull request merged**
