### PR TITLE
_dependency_source/pip: Log a warning and skip auditing for packages with invalid versions

### LINKED ISSUE #138: Version strings that don't conform to PEP 440 cause a failed audit
## Bug description

If `pip-audit` tries to audit an environment that contains a package with a version string that doesn't conform to PEP 440, it will fail like so:
```
dc@ubuntu:~$ pip-audit
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
\ Auditing appdirs (1.4.4)WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: apturl (0.5.2)
\ Auditing bcrypt (3.2.0)  WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: binwalk (2.2.1)
* Auditing bracex (2.1.1)  WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: brlapi (0.8.2)
| Auditing colored-traceback (0.3.0) WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: command-not-found (0.3)
\ Auditing cryptography (3.3.2)      WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: cupshelpers (1.0)
| Auditing decorator (4.4.2)            WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: defer (1.0.6)
/ Auditing intervaltree (3.1.0)         WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: iotop (0.6)
* Auditing kiwisolver (1.3.1)           WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: language-selector (0.1)
\ Auditing lockfile (0.12.2)            WARNING:pip_audit._service.pypi:warning: Dependency not found on PyPI and could not be audited: louis (3.16.0)
/ Auditing pytest (6.2.5)
Traceback (most recent call last):
  File "/home/dc/.local/lib/python3.9/site-packages/pip_audit/_dependency_source/pip.py", line 65, in collect
    dep = Dependency(name=dist.name, version=Version(str(dist.version)))
  File "/home/dc/.local/lib/python3.9/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '2.2.0-ubuntu0.21.04.1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dc/.local/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/home/dc/.local/lib/python3.9/site-packages/pip_audit/_cli.py", line 212, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/home/dc/.local/lib/python3.9/site-packages/pip_audit/_audit.py", line 60, in audit
    yield from self._service.query_all(specs)
  File "/home/dc/.local/lib/python3.9/site-packages/pip_audit/_service/interface.py", line 82, in query_all
    for spec in specs:
  File "/home/dc/.local/lib/python3.9/site-packages/pip_audit/_dependency_source/pip.py", line 72, in collect
    raise PipSourceError("failed to list installed distributions") from e
pip_audit._dependency_source.pip.PipSourceError: failed to list installed distributions
```
This can happen if some Python packages weren't installed from PyPI. In this case, the `python-apt` package that comes bundled with Ubuntu has a version string that contains the actual Ubuntu distribution version.

## Reproduction steps 

1. Run `pip-audit` without any arguments.
2. Observe the failure.

## Expected behavior

Instead of failing on an invalid version string, it'd be better to log a warning and continue on with the audit similar to how we handle things [here](https://github.com/trailofbits/pip-audit/blob/main/pip_audit/_service/pypi.py#L157).

## Platform information

* OS name and version: Ubuntu Linux 21.04
* `pip-audit` version (`pip-audit -V`): 0.07
* Python version (`python -V` or `python3 -V`): N/A
* `pip` version (`pip -V` or `pip3 -V`): N/A

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Closes #138

### CODE REVIEW

**Comment by di** [comment]
Would it make sense to list dependencies that can't be audited in the summary / JSON output as well?

I also think this would be something users might want to influence whether the audit passes or fails. Perhaps we want a `--strict` mode that makes the presence of an unauditable dependency a failure?

**Comment by di** [comment]
(Doesn't have to happen in this PR, just thinking about what we should do with unauditable dependencies long-term)

**Comment by tetsuo-cpp** [comment]
@di 
I like these ideas. I've created #141 and #142 to track them.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
LGTM, thanks!

**Pull request merged**
