### PR TITLE
_cli, resolvelib: Support for custom indices

### LINKED ISSUE #46: Support for custom indices
For the time being, our MVP is scoped to just support for PyPI. However, it's worth considering what we'd require in order to support custom package indices (whether PyPI mirrors or entirely separate private indexes).

Some potential points of issue:

* Our #23 adaptor will need to be sufficiently generic, adapting either PyPI or another index under the hood as configured.
* We *might* need custom index support from `pip-api`? This is unclear, since our only use of `pip-api` in these contexts would be for requirements parsing, and the requirements file *itself* shouldn't make any references to the index.

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Closes #46

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
I'll spin up a DevPi instance tomorrow to test this out more thoroughly.

**Comment by woodruffw** [comment]
Overall structure LGTM! I agree about the additional testing.

**Comment by di** [comment]
> I'll spin up a DevPi instance tomorrow to test this out more thoroughly.

You might be able to test with https://test.pypi.org instead, could be easier.

**Comment by tetsuo-cpp** [comment]
> > I'll spin up a DevPi instance tomorrow to test this out more thoroughly.
> 
> You might be able to test with https://test.pypi.org instead, could be easier.

Thanks! I did some testing with the test PyPI.

If my requirement simply says `pip`, it audits 22.0.3 from prod PyPI since it is a later version than anything on the test PyPI. If I constrain to `pip==18.1`, I can get it to audit the test PyPI version.

**Review by di — APPROVED** [review]

**Review by woodruffw — APPROVED** [review]
Awesome, LGTM!

**Pull request merged**
